version: '3.8'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    networks:
      - shared

networks:
  shared:
    driver: bridge